import { ChessType } from "types/ChessType";

//체스 말 처음 데이터
export const ChessBoardItems: ChessType[][] = [
  [
    {
      object: 11,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 9,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 13,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 100,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 30,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 13,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 9,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 11,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
  ],
  [
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "black",
    },
  ],
  [
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
  ],
  [
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
  ],
  [
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
  ],
  [
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
    {
      object: 0,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "",
    },
  ],
  [
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 1,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
  ],
  [
    {
      object: 11,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 9,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 13,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 100,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 30,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 13,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 9,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
    {
      object: 11,
      selected: false,
      isLine: false,
      canCaught: false,
      team: "white",
    },
  ],
];
